using help

diff --git a/.github/workflows/multiple job.yaml b/.github/workflows/multiple job.yaml
--- a/.github/workflows/multiple job.yaml
+++ b/.github/workflows/multiple job.yaml
@@ -11,14 +11,14 @@ jobs:
       run: sudo apt-get update && sudo apt-get install figlet -y
 
     - name: Execute figlet CMD
-      run: figlet "Run for cover, I am a dragon" > dragon.txt
+      run: figlet "Run for cover, I need help" >> help.txt
 
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
-        name: dragon-artifact
-        path: dragon.txt
-        
+        name: help-artifact
+        path: help.txt
+
   test_job_2:
     needs: build_job_1
     runs-on: ubuntu-latest
@@ -26,8 +26,8 @@ jobs:
     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
-        name: dragon-artifact
-        path: ./downloaded_artifacts/
+        name: help-artifact
+        path: help.txt
 
     - name: List files in downloaded_artifacts directory
       run: ls -l ./downloaded_artifacts/
@@ -36,7 +36,7 @@ jobs:
       run: cat ./downloaded_artifacts/dragon.txt
 
     - name: Test file exists
-      run: grep -i "dragon" ./downloaded_artifacts/dragon.txt || (echo "String 'dragon' not found!" && exit 1)
+      run: grep -i "help" help.txt || (echo "String 'help' not found!" && exit 1)
 
   deploy_job_3:
     needs: [test_job_2, build_job_1]
@@ -45,8 +45,8 @@ jobs:
     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
-        name: dragon-artifact
-        path: ./downloaded_artifacts/
+        name: help-artifact
+        path: help.txt
 
     - name: Read file
-      run: cat ./downloaded_artifacts/dragon.txt
+      run: cat help.txt
