push

diff --git a/.github/workflows/second-example.yaml b/.github/workflows/second-example.yaml
--- a/.github/workflows/second-example.yaml
+++ b/.github/workflows/second-example.yaml
@@ -24,9 +24,15 @@ jobs:
       # - name: Checkout repository
       #   uses: actions/checkout@v4
 
-      - name: Install cosway program
-        run:  wget -q -O cosway https://example.com/path/to/cosway || echo "Download failed"
-              chmod +x cosway || echo "Chmod failed"
+      - name: Download cosway
+        run: |
+          wget -q -O cosway https://example.com/path/to/cosway || echo "Download failed"
+          chmod +x cosway || echo "Chmod failed"
+      - name: Check if cosway exists
+        run: ls -l cosway
+
+      - name: Add cosway to PATH
+        run: echo "${{ github.workspace }}" && export PATH="${{ github.workspace }}:$PA
               
       - name: Check if cosway exists
         run: ls -l cosway
